name: .NET Core develop

on: 
  push:
    branches:    
      - develop  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101
    - run: dotnet build /DBInline/DBInline.csproj
